# Site settings
title: "nucl.ai Conference, 20-22 July 2015, Vienna/Austria."
email: team@aigamdev.com
description: >
  The largest worldwide conference about Artificial Intelligence applications
  in interactive media, training & simulations, and digital entertainment.
baseurl: "" # the subpath of your site, e.g. /blog/ <- in gh-pages must be a project name
url: "http://nucl.ai" # the base hostname & protocol for your site
twitter_username: aigamedev
github_username:  aigamedev

# Build settings
markdown: kramdown
exclude: [coffee]
